### ISSUE TITLE
ERROR:  Out of DMA buffer segment

### ISSUE THREAD

**Issue by davidzengxhsh** [heterodb/pg-strom#295]
I am running a multiple sql(tpc-ds q19) on the GPU with commit 27c778bc9519.
The first time running is completed successful. But the second time is crashed with "ERROR:  Out of DMA buffer segment". I checked the memory usage status of /dev/shm:
1) When the server is started
    $ df -h |grep /dev/shm
tmpfs                254G  4.1G  250G   2% /dev/shm
2) During the 1st running
   $ df -h |grep /dev/shm
tmpfs                254G   99G  156G  39% /dev/shm
3) After the 1st running finished
   $ df -h |grep /dev/shm
tmpfs                254G   31G  224G  12% /dev/shm
4) During the 2nd running
   $ df -h |grep /dev/shm
tmpfs                254G   99G  156G  39% /dev/shm

And then is will crashed with "ERROR:  Out of DMA buffer segment" .
It seems that the memory is not totally released after the 1st time running. In step 3) there is still 31G memory used, which makes the step 4) failed without enough memory available.

**Comment by kaigai** [comment]
You are right...
Even though ```dmaBufferCleanupOnPostmasterExit()``` cleans up shared memory segment but only when postmaster process is shutting down; it is a case for a normal shutdown.
On the other hands, it is danger to force releasing shared memory segment on crash of GPU server exit, because other backend may still reference these segment.
Let me investigate a best way to detach these segment safety.

**Comment by kaigai** [comment]
Now PG-Strom v2.0 will not use shared memory segment for as DMA source.
So, we don't allocate shared memory, thus no need to cleanup these segments.
