### ISSUE TITLE
Support for tensor cores in Nvidia Titan V?

### ISSUE THREAD

**Issue by stenerikbjorling** [heterodb/pg-strom#316]
Since Nvidia have released Titan V with a Volta processor the question is if there are any thoughts on integrating support for tensor core processing abilities in pg-strom. Use of tensors should massively accelerate aggregation computations etc.

Thanks and take care, Stene

**Comment by kaigai** [comment]
We have no plan to use Tensor cores, because ...
1. It internally use FP16, however, most of FP aggregate functions in PostgreSQL uses FP64. Use of Tensor cores cannot guarantee the accuracy.
1. It requires highly optimized data structure for the Tensor operations, however, it is not suitable to process unexpected number of input.
1. Even if calculation on GPU gets more and more fast, data transfer between RAM/SSD and GPU still dominate the performance.

So, it is too early to utilize the Tensor cores by SQL workloads.

On the other hands, it might be valuable on PL/CUDA routines.

**Comment by stenerikbjorling** [comment]
The PL/CUDA aspects are the ones that interests me. I guess that you are looking into that already,

Take care, Stene

**Comment by kaigai** [comment]
Likely, add support of cuBLAS library makes possible to use Tensor cores (according to the introduction by NVIDIA).
