### ISSUE TITLE
Pg_strom potential support for Agensgraph

### ISSUE THREAD

**Issue by stenerikbjorling** [heterodb/pg-strom#342]
Agensgraph is a fork of Postgres allowing the creation and usage of graph databases using Postgres as its foundation with all the existing functions of Postgres. Thus - would the combination of Agensgraph and pg_strom be a nice fit to speed up analysis etc. as you see it?

Take care, all the best...

Stene

**Comment by kaigai** [comment]
Sorry, I'm not certain about Agensgraph technology. So, it is not certain whether they can use PG-Strom to accelerate its workloads.
However, from our experiment in technology marketing for the recent 4 years, we have not met users who concern about the workloads that is suitable for graph database. Right now, I don't think it has higher priority than other development items.
https://github.com/heterodb/pg-strom/wiki/003:-Development-Roadmap#post-v20-features-since-apr-2018
