### ISSUE TITLE
run agg through MPS ,cuda error occured

### ISSUE THREAD

**Issue by littlexzt** [heterodb/pg-strom#348]
I run MPS control daemon in single user mode,and then start pg(9.6+pg_strom2.0).it's ok to run scan or join(without agg),and i can see the nvidia-cuda-mps-server process by run command nvidia-smi.but when i run SQLs that including agg,such as select max(id) from t1,it return as this:
ERROR:(cuda_program.c:1410) failed on cuModuleLoadData:CUDA_ERROR_NOT_SUPPORTED - operation not supported
i wonder if it's because that cudacode for agg contains Dynamic Parallelism stuff ,i see Document for Nvidia MPS said program will failed in cuModuleLoad if cudacode contains Dynamic Parallelism stuff. Or,maybe i was wrong in some steps using pg_strom2.0.

**Comment by kaigai** [comment]
Hmm. It may be a good point.
The current version of GpuPreAgg does not use any dynamic-parallelism stuff because of too much synchronization cost, use of `cudaDeviceSynchronize()` might be considered as something related to dynamic-parallelism.

I'll check this scenario next to the #344 and #347 .

**Comment by kaigai** [comment]
Likely, your estimation is right.
Once I commented out all the `cudaDeviceSynchronize` in `cuda_gpupreagg.h`, it works under MPS-daemon. (It is rarely used to synchronize hash-size adjustment if estimation would be too small.)

However, I don't plan to change the related logic immediately because ...

1. We have no easy alternatives right now (CUDA 9.1, at least), however, it is a core logic to adjust hash-table size of GpuPreAgg on the demand.
1. NVIDIA's developer also agree that MPS should support dynamic parallelism in the future version.
    Find "kaigai" from the https://devblogs.nvidia.com/inside-volta/ .

So, I like to recommend to turn off MPS until this feature gets supported by NVIDIA.
Documentation needs update.

Thanks,

**Comment by littlexzt** [comment]
well,thank you for your help!

**Comment by kaigai** [comment]
Now we don't recommend MPS.
