### ISSUE TITLE
Wrong result of GpuPreAgg if combined with GpuJoin

### ISSUE THREAD

**Issue by exialin** [heterodb/pg-strom#365]
Hello @kaigai. I found the result is incorrect if `pg_strom.pullup_outer_join` is set to `on`.

Here are some examples:
```
testdb=# set pg_strom.pullup_outer_join = off;
testdb=# select count(*) from j1 join j2 on j1.c2 = j2.c2;
 count
--------
 30603
(1 row)
testdb=# select min(j2.c2) from j1 join j2 on j1.c2 = j2.c2;
 min
-----
   1
(1 row)

testdb=# set pg_strom.pullup_outer_join = on;
testdb=# select count(*) from j1 join j2 on j1.c2 = j2.c2;
 count
--------
   9861
(1 row)
testdb=# select min(j2.c2) from j1 join j2 on j1.c2 = j2.c2;
 min
-----
   2
(1 row)
```

The result is still wrong if `GROUP BY` is added. Tested with the latest commit 0f90503d2b6ff4238fe037431eeacdc0938bc3c7.

Regards

**Comment by kaigai** [comment]
I'll look at the problem this weekend. Now busy until Friday...

**Comment by kaigai** [comment]
e933c0f8b6ee086f6aeddb47231588cb39803883 Fixed the problem.

On the combined execution mode, GpuPreAgg references the `kds_slot` buffer that is the result buffer for GpuJoin. If GpuJoin generates more rows than `kds_slot` size, GpuJoin is once suspended and GpuPreAgg runs reduction operation, then it resumes the GpuJoin.
In the prior code, GpuPreAgg didn't rewind the read offset counter, so second or later execution
quits the GPU kernel immediately because they though the supplied `kds_slot` buffer is already read.
