### ISSUE TITLE
does pgstrom support nvidia P2000 ?

### ISSUE THREAD

**Issue by changchichung** [heterodb/pg-strom#441]
I try to run pgstrom with my old gt 720 VGA , but it`s not supported. so I want to purchase a new vga card , the vendor recommended nvidia P2000 , which is not in the supported gpu list

https://github.com/heterodb/pg-strom/wiki/001:-GPU-Availability-Matrix
But nvidia P2000 is a graphic card with pascal architecture .

so I`m wondering if nvidia P2000 supported by pgstrom or not ? or should I just buy  a GTX 1080 since RTX 2800 was not tested ?

**Comment by kaigai** [comment]
It depends on your interest and purpose.

Our recommendation is Tesla GPUs that have `with NVMe == Yes`, because it can support SSD-to-GPU Direct SQL that is the reason why people are interested in PG-Strom.
However, it is not a cheap device for individual persons.

I **expect** NVIDIA P2000 is workable, however, not tested and its hardware resource is not enough.

**Comment by changchichung** [comment]
thanks , I will consider 1080/2080 instead P2000 .
