### ISSUE TITLE
Unable to start postgres 12 after install of pg_strom

### ISSUE THREAD

**Issue by dewoller** [heterodb/pg-strom#469]
Thanks so much for building this.  Improves my workflow immensely.  

I was able to compile V2 for Ubuntu, but after installation, I get the following error:

```
LOG:  PG-Strom: GPU0 GeForce GTX TITAN X - CC 5.2 is not supported
FATAL:  PG-Strom: no supported GPU devices found
```
The availability matrix at https://github.com/heterodb/pg-strom/wiki/001:-GPU-Availability-Matrix mentions that the TITAN X, while untested, should work. 

Is it because I have CC 5.2? If yes, can you tell me what I need to do to change it to CC 6.1?  Do you mean that the nvidia drivers need to be compiled with a newer version of gcc?

Thanks
Dennis

**Comment by kaigai** [comment]
> Is it because I have CC 5.2?
>
Yes. Computing Capability (CC) is a version number of the hardware.
So, I have to recommend to use newer generation of GPU devices.
Because of memory management system renew at Pascal generation,
we stopped to support Kepler/Maxwell architecture a few years before.

https://github.com/heterodb/pg-strom/wiki/100:-FAQ#why-maxwellkepler-gpus-are-not-supported
