### ISSUE TITLE
Some questions about cuda code

### ISSUE THREAD

**Issue by Cerdore** [heterodb/pg-strom#535]
Actually, I would like to implement the radix join strategy based on your code, but radix join requires me to repartition the data first. This means that I need to reorder the entire data. So I have some questions about **kernel_data_store**.
1. Whether the runtime will use multiple kernel_data_store to transfer data？
2. If there are more than one kds is how to divide the data, how to distinguish between the inner and outer table ?( I read the **_gpuNestLoop_** part of the code feels like the inner and outer table of the data is present in the same kds)
3. In the function _gpujoin_process_inner_join_, for the case of "**_pds_src->kds.format = KDS_FORMAT_ROW_**", I only found the code _**m_kds_src = (CUdeviceptr)&pds_src->kds;**_, but not function for data copy like cuMemHtoD. I also didn't find cuMemHtoD in gpu_load_source.
4. Regarding the repartitioning of data, I plan to put it before the kernel function **kern_gpujoin_main**. But I do not know if this is reasonable. 

I hope you can give some valuable advice. Thank you!

**Comment by kaigai** [comment]
1. Yes. In case when GpuJoin involves multiple inner-tables. See `kern_multirels` and `KERN_MULTIRELS_INNER_KDS()`.
2. See `gpujoin_next_task`. It crams the outer tuples into the kds buffer until it has free space (or end of the scan).
3. m_kds_src is allocated on the CUDA managed memory area. The CUDA driver transfers the host data to the device using page fault mechanism, so we don't need to use cuMemHtoD() mechanism explicitly.
4. Table-joining itself is not computing intensive workloads. So, I like to bet preprocessing of the inner/outer data don't make sense so much....

**Comment by Cerdore** [comment]
Thank you for your timely response! 

But Sorry. I may be a bit stupid and still have some doubts.

1. Will there be multiple kds even when there are only two tables join?
2. The inner table is obtained by` GpuJoinInnerPreload`, and the data transfer also used CUDA Unified Memory if `gj_sstate->phase == INNER_PHASE__SCAN_RELATIONS`, right?
4. Although Table-joining itself is not computing intensive workloads, hashing is computationally intensive. It looks like for the inner table key, you are doing the hashing on the CPU side. Also I don't know if radix join will work for fully utilizing shared memory. So difficult...

**Comment by kaigai** [comment]
1. In case of two tables join, GpuJoin uses only two KDS for a chunk of outer relation and inner relation on the `kern_multirels`.
2. Inner tables are exceptional. It uses traditional device-only memory (because it can be shared by multiple PostgreSQL backends), so we have to call `cuMemcpyHtoD` at `innerPreloadLoadDeviceBuffer`. After preloading of entire inner relations.
3. GpuJoin runs hashing of inner tables key on CPU-side, because it assumes inner tables are relatively much smaller than the outer relation. Most of hashing are performed on the outer tables, and it is processed on GPU-side in parallel.

Sorry, I had not investigated radix join so deeply. Is it suitable algorithm for non-uniformed key distribution, variable-length join keys, and NULL variables in some cases? At least, it can happen on behalf of PostgreSQL.

**Comment by Cerdore** [comment]
Thanks! It's great to meet a developer like you when I'm at a loss！

In fact, almost no databases are using the radix join.[ Radix hash join](https://15721.courses.cs.cmu.edu/spring2016/slides/11.pdf) is a variant of hash join. So the case you mentioned should be solved if the hash join can be solved.
