### ISSUE TITLE
Support for AMD GPUs

### ISSUE THREAD

**Issue by rksinghfbd** [heterodb/pg-strom#588]
What is the plan to support AMD GPUs? 

I am looking for the team / leads which implemented this features. Please feel free to reach out to me for further clarifications or discussion. 

Ravi.singh@amd.com

Regards
Ravi Singh

**Comment by rksinghfbd** [comment]
I am happy to fund the porting and testing.

**Comment by kaigai** [comment]
PG-Strom v3.x series has been tightly connected with NVIDIA's feature because it internally generates the native CUDA C++ code thus it had been hard to port other GPUs.
On the other hands, the upcoming PG-Strom v5.0 will use its own pseudo code set to support both of GPU and DPU.
Therefore, the support of AMD GPUs is not a big challenge.

From the technology viewpoint, the most characteristic PG-Strom's feature is GPU-Direct SQL; that stand on the NVIDIA's GPUDirect Storage technology. I'm not certain whether AMD can provide similar functionalities.
IIRC, I saw an official documentation introduced the way to write up kernel module to intermediate P2P-RDMA somewhere, as long as here is no patent problems, it is possible to implement AMD GPU based GPU-Direct SQL but only for local NVME-SSDs; like as prior version of PG-Strom.

According to the publication from AMD, the upcoming MI300 GPU is integrated with CPU that shares same physical memory.
If it is right for our expectation, it may be possible to pull out the ideal storage performance with computational performance.

**Comment by kaigai** [comment]
This topic has not been active for two months.
